### ISSUE TITLE
"make all" fails because gradle is not installed

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-wh96#1]
The error is:

> root@8dd107072736:/depsolver/to-test# make all
> ./gradlew build -q
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
> Makefile:4: recipe for target 'build' failed
> make: *** [build] Error 1

See this screencast for details: https://asciinema.org/a/Tghm34YYBVO15bZ7aZKrPiSiQ
In makefile, you need to add commands for installing gradle.

**Comment by ghost** [comment]
Using the gradle wrapper should mean that gradle does not need to be installed on the target machine. The error was in  the .gitignore which meant gradle-wrapper.jar was being excluded from the repository.

Fixed in b3418b23b98ee1affce11bf83bb1ed58de0be0b9
